# Generated by Django 2.2 on 2020-09-19 07:53

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Order = apps.get_model('webapp', 'Order')
    OrderProduct = apps.get_model('webapp', 'OrderProduct')
    for order in Order.objects.all():
        for product in order.products.all():
            OrderProduct(
                product=product,
                order=order,
                amount=product.amount
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200919_0752'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
